version: '2.1'
services:
  notebook:
    build: .
    container_name: data-jam-notebook
    environment:
      - DATABASE=postgres://postgres:password@postgres:5432/data-jam
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/data-jam

  postgres:
    image: postgres:9.6
    container_name: data-jam-db
    environment:
      - POSTGRES_DB=data-jam
      - POSTGRES_PASSWORD=password
    volumes:
      - data_postgres:/var/lib/postgresql/data

volumes:
  data_postgres: {}
